---
ms.openlocfilehash: 69b0a9165715c6cd0e8de37ddb4abad94de2b102
ms.sourcegitcommit: e739004291428ce83f14b9d49f1e9dfaa3762dde
ms.translationtype: HT
ms.contentlocale: de-DE
ms.lasthandoff: 02/05/2022
ms.locfileid: "138051091"
---
# <a name="once"></a>once

Eine Funktion nur einmal aufrufen.

## <a name="usage"></a>Nutzung

```javascript
var once = require('once')

function load (file, cb) {
  cb = once(cb)
  loader.load('file')
  loader.once('load', cb)
  loader.once('error', cb)
}
```

Oder dem Function.prototyp auf verantwortungsvolle Weise hinzufügen:

```javascript
// only has to be done once
require('once').proto()

function load (file, cb) {
  cb = cb.once()
  loader.load('file')
  loader.once('load', cb)
  loader.once('error', cb)
}
```

Ironischerweise macht das Prototypfeature dieses Modul doppelt so kompliziert wie nötig.

Um zu überprüfen, ob Ihre Funktion aufgerufen wurde, verwenden Sie `fn.called`. Sobald die Funktion zum ersten Mal aufgerufen wird, wird der Rückgabewert der ursprünglichen Funktion in `fn.value` gespeichert, und nachfolgende Aufrufe geben weiterhin diesen Wert zurück.

```javascript
var once = require('once')

function load (cb) {
  cb = once(cb)
  var stream = createStream()
  stream.once('data', cb)
  stream.once('end', function () {
    if (!cb.called) cb(new Error('not found'))
  })
}
```

## `once.strict(func)`

Einen Fehler auslösen, wenn die Funktion zweimal aufgerufen wird.

Von einigen Funktionen wird erwartet, dass sie nur einmal aufgerufen werden. Die Verwendung von `once` für solche Funktionen würde logische Fehler potenziell verdecken.

Im folgenden Beispiel muss die `greet`-Funktion den Rückruf nur einmal aufrufen:

```javascript
function greet (name, cb) {
  // return is missing from the if statement
  // when no name is passed, the callback is called twice
  if (!name) cb('Hello anonymous')
  cb('Hello ' + name)
}

function log (msg) {
  console.log(msg)
}

// this will print 'Hello anonymous' but the logical error will be missed
greet(null, once(msg))

// once.strict will print 'Hello anonymous' and throw an error when the callback will be called the second time
greet(null, once.strict(msg))
```
